-- Receitas de tuning geradas a partir de E:\QBOXPIERRE\downloads\pecas_tuning.lua
-- Arquivo de referencia Lua. Para importar no banco, use receita_tuning.sql.

return {
    craft_id = 905311,
    craft_name = "Pecas Tuning",
    items = {
        {
            item = "pistao_racing_forged",
            item_label = "Pistao Racing Forged",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "biela_street_performance",
            item_label = "Biela Street Performance",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "anel_pistao_high_compression",
            item_label = "Anel Pistao High Compression",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "bronzina_biela_powerline",
            item_label = "Bronzina Biela Powerline",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "bronzina_mancal_prodrive",
            item_label = "Bronzina Mancal Prodrive",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "parafuso_biela_ultrabolt",
            item_label = "Parafuso Biela Ultrabolt",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "parafuso_cabecote_headlock",
            item_label = "Parafuso Cabecote Headlock",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "junta_cabecote_multiseal",
            item_label = "Junta Cabecote Multiseal",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "correia_dentada_powerbelt",
            item_label = "Correia Dentada Powerbelt",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "bomba_oleo_highflow_oil",
            item_label = "Bomba Oleo Highflow Oil",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "turbo_garret_1",
            item_label = "Garrett GT1548",
            time = 35,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "bico_injetor_megaflow",
            item_label = "Bico Injetor Megaflow",
            time = 22,
            amount = 1,
            level = 0,
            recipe = {
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "bomba_combustivel_fuelmax_pro",
            item_label = "Bomba Combustivel Fuelmax Pro",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "regulador_pressao_fuelcontrol_x",
            item_label = "Regulador Pressao Fuelcontrol X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "mangueira_combustivel_flexfuel",
            item_label = "Mangueira Combustivel Flexfuel",
            time = 22,
            amount = 1,
            level = 0,
            recipe = {
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "linha_combustivel_steelflow",
            item_label = "Linha Combustivel Steelflow",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "flauta_fuel_rail_performance",
            item_label = "Flauta Fuel Rail Performance",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "corpo_borboleta_airflow_70mm",
            item_label = "Corpo Borboleta Airflow 70MM",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "coletor_admissao_air_intake_pro",
            item_label = "Coletor Admissao Air Intake Pro",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "filtro_ar_powerfilter",
            item_label = "Filtro AR Powerfilter",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "duto_admissao_cold_air_pipe",
            item_label = "Duto Admissao Cold Air Pipe",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "mangote_admissao_turboflex",
            item_label = "Mangote Admissao Turboflex",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "abracadeira_lockclamp_pro",
            item_label = "Abracadeira Lockclamp Pro",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "retentor_motor_oilguard",
            item_label = "Retentor Motor Oilguard",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "tensor_correia_autotension_pro",
            item_label = "Tensor Correia Autotension Pro",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "polia_virabrequim_lightspin",
            item_label = "Polia Virabrequim Lightspin",
            time = 21,
            amount = 1,
            level = 0,
            recipe = {
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "turbo_garret_2",
            item_label = "Garrett GT2056",
            time = 36,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 5 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "intercooler_megacooler",
            item_label = "Intercooler Megacooler",
            time = 33,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "tubulacao_intercooler_boostpipe",
            item_label = "Tubulacao Intercooler Boostpipe",
            time = 21,
            amount = 1,
            level = 0,
            recipe = {
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "mangueira_pressao_hyperflow",
            item_label = "Mangueira Pressao Hyperflow",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "conexao_aluminio_alloylink",
            item_label = "Conexao Aluminio Alloylink",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "radiador_agua_cooling_pro_x",
            item_label = "Radiador Agua Cooling Pro X",
            time = 35,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "reservatorio_expansao_cooltank",
            item_label = "Reservatorio Expansao Cooltank",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "tampa_radiador_pressure_cap_x",
            item_label = "Tampa Radiador Pressure Cap X",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "ventoinha_airforce_fan",
            item_label = "Ventoinha Airforce Fan",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "radiador_oleo_oilcooler_racing",
            item_label = "Radiador Oleo Oilcooler Racing",
            time = 36,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 5 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "mangueira_oleo_oilline_pro",
            item_label = "Mangueira Oleo Oilline Pro",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 1 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "coletor_escape_turbo_header",
            item_label = "Coletor Escape Turbo Header",
            time = 35,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "downpipe_powerdown_x",
            item_label = "Downpipe Powerdown X",
            time = 36,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 5 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "escape_esportivo_fullflow",
            item_label = "Escape Esportivo Fullflow",
            time = 33,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "catalisador_racecat",
            item_label = "Catalisador Racecat",
            time = 35,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "wastegate_boostcontrol",
            item_label = "Wastegate Boostcontrol",
            time = 36,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 5 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "valvula_blowoff_turborelease",
            item_label = "Valvula Blowoff Turborelease",
            time = 33,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "pescador_oleo_deepflow",
            item_label = "Pescador Oleo Deepflow",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "carter_oilpan_performance",
            item_label = "Carter Oilpan Performance",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "defletor_oleo_oilbaffle_pro",
            item_label = "Defletor Oleo Oilbaffle Pro",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "tampa_valvulas_valvecover_x",
            item_label = "Tampa Valvulas Valvecover X",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "turbo_garret_3",
            item_label = "Garrett GT3071R",
            time = 36,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 5 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "embreagem_stagex_racing",
            item_label = "Embreagem Stagex Racing",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "plato_pressureforce",
            item_label = "Plato Pressureforce",
            time = 31,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "disco_ceramico_ceramicgrip",
            item_label = "Disco Ceramico Ceramicgrip",
            time = 32,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "volante_motor_lightflywheel_pro",
            item_label = "Volante Motor Lightflywheel Pro",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "garfo_embreagem_shiftfork_x",
            item_label = "Garfo Embreagem Shiftfork X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "atuador_embreagem_hydroclutch",
            item_label = "Atuador Embreagem Hydroclutch",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "rolamento_embreagem_spinlock",
            item_label = "Rolamento Embreagem Spinlock",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "trambulador_shortshift_pro",
            item_label = "Trambulador Shortshift Pro",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "cabo_engate_gearlink",
            item_label = "Cabo Engate Gearlink",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "engrenagem_cambio_gearset",
            item_label = "Engrenagem Cambio Gearset",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "sincronizadores_syncrotech",
            item_label = "Sincronizadores Syncrotech",
            time = 31,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "diferencial_lockdiff_pro",
            item_label = "Diferencial Lockdiff Pro",
            time = 32,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "semieixo_torqueshaft",
            item_label = "Semieixo Torqueshaft",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "homocinetica_drivejoint_x",
            item_label = "Homocinetica Drivejoint X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "coxin_motor_powermounts",
            item_label = "Coxin Motor Powermounts",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "coxin_cambio_gearmount_pro",
            item_label = "Coxin Cambio Gearmount Pro",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "suporte_cambio_transbracket_x",
            item_label = "Suporte Cambio Transbracket X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "tampa_cambio_gearcover_pro",
            item_label = "Tampa Cambio Gearcover Pro",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "eixo_primario_input_shaft_pro",
            item_label = "Eixo Primario Input Shaft Pro",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "eixo_secundario_output_shaft_x",
            item_label = "Eixo Secundario Output Shaft X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "rolamento_cambio_gearbearings",
            item_label = "Rolamento Cambio Gearbearings",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 3 },
            },
        },
        {
            item = "kit_reparo_cambio_rebuild_kit",
            item_label = "Kit Reparo Cambio Rebuild Kit",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "flange_cambio_driveflange_x",
            item_label = "Flange Cambio Driveflange X",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "junta_carter_oilseal_pro",
            item_label = "Junta Carter Oilseal Pro",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "junta_tampa_valvulas_sealcover_x",
            item_label = "Junta Tampa Valvulas Sealcover X",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "prisioneiro_cabecote_headstuds",
            item_label = "Prisioneiro Cabecote Headstuds",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "guia_valvula_valveguide_x",
            item_label = "Guia Valvula Valveguide X",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "sede_valvula_valveseat_pro",
            item_label = "Sede Valvula Valveseat Pro",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "mola_valvula_valvespring_racing",
            item_label = "Mola Valvula Valvespring Racing",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "retentor_valvula_valveseal_pro",
            item_label = "Retentor Valvula Valveseal Pro",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "turbo_garret_4",
            item_label = "Garrett GTX3582R",
            time = 33,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "coilover",
            item_label = "Coilover",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "brake_level_1",
            item_label = "Freio Ferodoz",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "brake_level_2",
            item_label = "Freio StoptechX",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 1 },
            },
        },
        {
            item = "brake_level_3",
            item_label = "Freio Wilhood",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "brake_level_4",
            item_label = "Freio Brempo",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "tire_drag",
            item_label = "Pneus Drag",
            time = 24,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 3 },
                { item = "iron", label = "Iron", amount = 1 },
            },
        },
        {
            item = "tire_slick",
            item_label = "Pneus Slick",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 4 },
                { item = "titanium", label = "Titanium", amount = 1 },
            },
        },
        {
            item = "tire_semislick",
            item_label = "Pneus Semi Slick",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 5 },
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 1 },
            },
        },
        {
            item = "tire_race",
            item_label = "Pneus Race",
            time = 31,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 5 },
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 2 },
            },
        },
        {
            item = "tire_sport",
            item_label = "Pneus Sport",
            time = 24,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 3 },
                { item = "iron", label = "Iron", amount = 1 },
            },
        },
        {
            item = "tire_street",
            item_label = "Pneus Street",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 4 },
                { item = "titanium", label = "Titanium", amount = 1 },
            },
        },
        {
            item = "tire_drift",
            item_label = "Pneus Drift",
            time = 30,
            amount = 1,
            level = 0,
            recipe = {
                { item = "rubber", label = "Rubber", amount = 5 },
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 1 },
            },
        },
        {
            item = "barra_estabilizadora",
            item_label = "Barra Estabilizadora",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "amortecedor",
            item_label = "Amortecedor",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "mola",
            item_label = "Mola",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "bandeja",
            item_label = "Bandeja",
            time = 25,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "titanium", label = "Titanium", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "bieleta",
            item_label = "Bieleta",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 4 },
            },
        },
        {
            item = "bucha",
            item_label = "Bucha",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "disco_freio",
            item_label = "Disco de Freio",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "pastilha_freio",
            item_label = "Pastilha de Freio",
            time = 27,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "pivo",
            item_label = "Pivo",
            time = 20,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "diferencial_pro",
            item_label = "Diferencial Pro",
            time = 37,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 3 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "freio_mao_drift",
            item_label = "Freio Mao Drift",
            time = 33,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 3 },
                { item = "titanium", label = "Titanium", amount = 4 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
        {
            item = "kit_angulo",
            item_label = "Kit Angulo",
            time = 26,
            amount = 1,
            level = 0,
            recipe = {
                { item = "iron", label = "Iron", amount = 2 },
                { item = "rubber", label = "Rubber", amount = 2 },
            },
        },
    }
}

